language: go

sudo: true

go:
  - 1.5
  - tip

language: go
go: 
 - 1.3.3
 - 1.4.2
 - 1.5.1
 - release
 - tip

script:
 - go test -v ./...

install:
  - sudo apt-get update -qq
  - apt-get install libsdl2{,-mixer,-image,-ttf}-dev
  - go get -v github.com/veandco/go-sdl2/sdl{,_mixer,_image,_ttf}