language: go
go:
 - 1.5.1
 - release
 - tip

sudo: true

env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - sudo apt-get update -qq
  - apt-get install libsdl2{,-mixer,-image,-ttf}-dev
  - go get -v github.com/veandco/go-sdl2/sdl{,_mixer,_image,_ttf}
script:
  - go build
